spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false ##no es cliente, es servidor
    fetch-registry: false ## que no se registre a si mismo
    service-url:
      defaultZone: http://localhost:8761/eureka/